[package]
name = "library_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
clap = { version = "4.5.54", features = ["derive"] }
chrono = { version = "0.4.43", features = ["serde"] }
